backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "events"
    label: "Events"
    folder: "src/pages/events"
    create: true
    slug: "{{startsAt}}-{{slug}}"
    summary: "{{startsAt}}: {{type}} - {{title}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "event"}
      - {label: "Title", name: "title", widget: "string", hint: "The name of the event, e.g. Oaklands"}
      - {label: "Venue", name: "venueName", widget: "relation", collection: "venues", searchFields: ["title"], valueField: "title", displayField: "title", hint: "Where the event is taking place"}
      - {label: "Starts at", name: "startsAt", widget: "datetime", format: "YYYY-MM-DD HH:mm", hint: "The start time in local time"}
      - {label: "Type", name: "type", widget: "select", options: ["Group Run", "Meeting", "Race", "Social", "Track"]}
      - {label: "Terrain", name: "terrain", widget: "select", options: ["Cross Country", "Fell", "Mixed", "Road", "Track", "Trail"]}
      - {label: "Championship", name: "championshipName", widget: "relation", collection: "championships", searchFields: ["title"], valueField: "title", displayField: "title", required: false, hint: "If the event is part of a championship, add it here"}
      - {label: "Route", name: "routeName", widget: "relation", collection: "routes", searchFields: ["title"], valueField: "title", displayField: "title", multiple: true, required: false, hint: "If this event has routes, add them here"}
      - {label: "Session", name: "sessionName", widget: "relation", collection: "sessions", searchFields: ["title"], valueField: "title", displayField: "title", required: false, hint: "If this event is a track session, add it here"}
      - {label: "Information", name: "body", widget: "markdown", required: false, hint: "Additional information about the event."}
  - name: "venues"
    label: "Venues"
    folder: "src/pages/venues"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "venue"}
      - {label: "Title", name: "title", widget: "string", hint: "The name of the venue, e.g. Heaton Park"}
      - {label: "Address", name: "address", widget: "text", hint: "The postal address of the venue. Include a postcode if you can!"}
      - {label: "Location", name: "location", widget: "map", hint: "Select the location of the venue on the map", decimals: 6}
      - {label: "Information", name: "body", widget: "markdown", hint: "Useful information about the venue, e.g. car parking, public transport", required: false}
  - name: "championships"
    label: "Championships"
    folder: "src/pages/championships"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "championship"}
      - {label: "Title", name: "title", widget: "string", pattern: ['^[0-9]{4}(-[0-9]{2})?\s.+$', "The championship name must begin with the date"], hint: "The name of the championship, e.g. 2019-20 Cross Country Championship"}
      - {label: "Information", name: "body", widget: "markdown", hint: "Information about the championship, e.g. entry requirements, qualification criteria"}
  - name: "sessions"
    label: "Sessions"
    folder: "src/pages/sessions"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "session"}
      - {label: "Title", name: "title", widget: "string", hint: "The name of the session, e.g. 400m repeats"}
      - {label: "Information", name: "body", widget: "markdown", hint: "Information about the session, e.g. duration, number of reps"}
  - name: "routes"
    label: "Routes"
    folder: "src/pages/routes"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "route"}
      - {label: "Title", name: "title", widget: "string", hint: "The name of the route, e.g. Oaklands"}
      - {label: "Route", name: "routeTrack", widget: "map", type: "LineString", decimals: 6}
      - {label: "Information", name: "body", widget: "markdown", hint: "Information about the route, e.g. distance, directions, things to see"}
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
