backend:
  name: git-gateway
  branch: master

media_folder: static/media
public_folder: /media

collections:
  - name: "events"
    label: "Events"
    folder: "src/pages/events"
    create: true
    slug: "{{startsAt}}-{{slug}}"
    summary: "{{startsAt}}: {{type}} - {{eventKey}}"
    identifier_field: "eventKey"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "event"}
      - {label: "Title", name: "eventKey", widget: "string", hint: "The name of the event, e.g. Oaklands"}
      - {label: "Starts at", name: "startsAt", widget: "datetime", format: "YYYY-MM-DD HH:mm", hint: "The start time in local time"}
      - {label: "Venue", name: "venueForeignKey", widget: "relation", collection: "venues", searchFields: ["venueKey"], valueField: "venueKey", displayField: "venueKey", hint: "Where the event is taking place"}
      - {label: "Type", name: "eventType", widget: "select", options: ["Group Run", "Meeting", "Race", "Social", "Speedwork"]}
      - {label: "Terrain", name: "terrain", widget: "select", options: ["Cross Country", "Fell", "Mixed", "Road", "Track", "Trail"]}
      - {label: "Championship", name: "championshipForeignKey", widget: "relation", collection: "championships", searchFields: ["championshipKey"], valueField: "championshipKey", displayField: "championshipKey", required: false, hint: "If the event is part of a championship, add it here"}
      - {label: "Competition", name: "competitionForeignKey", widget: "select", options: ["Manchester Area Cross Country League", "South East Lancs Cross Country League"], required: false, hint: "Select if the event is part of a competition or league"}
      - {label: "Route", name: "routeForeignKey", widget: "relation", collection: "routes", searchFields: ["routeKey"], valueField: "routeKey", displayField: "routeKey", multiple: true, required: false, hint: "If this event has routes, add them here"}
      - {label: "Session", name: "sessionForeignKey", widget: "relation", collection: "sessions", searchFields: ["sessionKey"], valueField: "sessionKey", displayField: "sessionKey", required: false, hint: "If this event is a track session, add it here"}
      - {label: "Information", name: "body", widget: "markdown", required: false, hint: "Additional information about the event."}
  - name: "venues"
    label: "Venues"
    folder: "src/pages/venues"
    create: true
    slug: "{{slug}}"
    identifier_field: "venueKey"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "venue"}
      - {label: "Title", name: "venueKey", widget: "string", hint: "The name of the venue, e.g. Heaton Park"}
      - {label: "Address", name: "address", widget: "text", hint: "The postal address of the venue. Include a postcode if you can!"}
      - {label: "Location", name: "location", widget: "map", hint: "Select the location of the venue on the map", decimals: 6}
      - {label: "Information", name: "body", widget: "markdown", hint: "Useful information about the venue, e.g. car parking, public transport", required: false}
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: "blogKey"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "blogKey", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "championships"
    label: "Championships"
    folder: "src/pages/championships"
    create: true
    slug: "{{slug}}"
    identifier_field: "championshipKey"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "championship"}
      - {label: "Title", name: "championshipKey", widget: "string", pattern: ['^[0-9]{4}(-[0-9]{2})?\s.+$', "The championship name must begin with the date"], hint: "The name of the championship, e.g. 2019-20 Cross Country Championship"}
      - {label: "Terrain", name: "terrain", widget: "select", options: ["Cross Country", "Fell", "Mixed", "Road", "Track", "Trail"]}
      - {label: "Information", name: "body", widget: "markdown", hint: "Information about the championship, e.g. entry requirements, qualification criteria"}
  - name: "sessions"
    label: "Sessions"
    folder: "src/pages/sessions"
    create: true
    slug: "{{slug}}"
    identifier_field: "sessionKey"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "session"}
      - {label: "Title", name: "sessionKey", widget: "string", hint: "The name of the session, e.g. 400m repeats"}
      - {label: "Information", name: "body", widget: "markdown", hint: "Information about the session, e.g. duration, number of reps"}
  - name: "routes"
    label: "Routes"
    folder: "src/pages/routes"
    create: true
    slug: "{{slug}}"
    identifier_field: "routeKey"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "route"}
      - {label: "Title", name: "routeKey", widget: "string", hint: "The name of the route, e.g. Oaklands"}
      - {label: "Route", name: "routeTrack", widget: "map", type: "LineString", decimals: 6}
      - {label: "Information", name: "body", widget: "markdown", hint: "Information about the route, e.g. distance, directions, things to see"}
  - name: "info"
    label: "Info"
    folder: "src/pages/info"
    create: true
    slug: "{{slug}}"
    identifier_field: "infoKey"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "info"}
      - {label: "Title", name: "infoKey", widget: "string", hint: "Not displayed to end users"}
      - {label: "Championship", name: "forChampionshipKey", widget: "relation", collection: "championships", searchFields: ["championshipKey"], valueField: "championshipKey", displayField: "championshipKey", required: false, hint: "Select if this info relates to a championship"}
      - {label: "Competition", name: "forCompetitionKey", widget: "select", options: ["Manchester Area Cross Country League", "South East Lancs Cross Country League"], required: false, hint: "Select if this info relates to a competition"}
      - {label: "Type", name: "forEventType", widget: "select", options: ["Group Run", "Meeting", "Race", "Social", "Speedwork"], required: false, hint: "Select if this info relates to an event type"}
      - {label: "Terrain", name: "forTerrain", widget: "select", options: ["Cross Country", "Fell", "Mixed Terrain", "Road", "Track", "Trail"], required: false, hint: "Select if this info relates to a terrain"}
      - {label: "Info", name: "body", widget: "markdown", hint: "Reusable information, e.g. kit requirements, generic session structure, etc."}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "string", pattern: ['^.{,156}$', "The description can only contain a maximum of 156 characters"]}
          - {label: "Left block", name: "leftBlock", widget: "markdown"}
          - {label: "Right block", name: "rightBlock", widget: "markdown"}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "standard-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "string", pattern: ['^.{,156}$', "The description can only contain a maximum of 156 characters"]}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/about/committee/index.md"
        label: "Committee"
        name: "committee"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "committee-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "string", pattern: ['^.{,156}$', "The description can only contain a maximum of 156 characters"]}
          - {label: "Intro", name: "intro", widget: "markdown"}
          - label: "Members"
            name: "members"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Role", name: "role", widget: "string"}
              - {label: "Image", name: "image", widget: "image", allow_multiple: false}
              - {label: "Description", name: "description", widget: "markdown"}
      - file: "src/pages/about/london-marathon-place/index.md"
        label: "London Marathon place"
        name: "londonMarathonPlace"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "standard-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "string", pattern: ['^.{,156}$', "The description can only contain a maximum of 156 characters"]}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/about/rules/index.md"
        label: "Rules"
        name: "rules"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "rules-page"}
          - {label: "Title", name: "title", widget: "string", default: "Club rules"}
          - {label: "Description", name: "description", widget: "string", pattern: ['^.{,156}$', "The description can only contain a maximum of 156 characters"]}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Rules document", name: "rulesDocument", widget: "file"}
      - file: "src/pages/join/index.md"
        label: "Join"
        name: "join"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "join-page"}
          - {label: "Title", name: "title", widget: "string", default: "Join us"}
          - {label: "Description", name: "description", widget: "string", pattern: ['^.{,156}$', "The description can only contain a maximum of 156 characters"]}
          - {label: "How to join us", name: "howToJoinUs", widget: "markdown"}
          - {label: "Membership benefits", name: "membershipBenefits", widget: "markdown"}
          - {label: "Y Club facilities", name: "yClubFacilities", widget: "markdown"}
      - file: "src/pages/join/success/index.md"
        label: "Join - Success (First Claim)"
        name: "joinSuccessFirstClaim"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "standard-page"}
          - {label: "Title", name: "title", widget: "string", default: "Thanks for joining the club!"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/join/success-second-claim/index.md"
        label: "Join - Success (Second Claim)"
        name: "joinSuccessSecondClaim"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "standard-page"}
          - {label: "Title", name: "title", widget: "string", default: "Thanks for joining the club!"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/join/cancel/index.md"
        label: "Join - Cancel"
        name: "joinCancel"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "standard-page"}
          - {label: "Title", name: "title", widget: "string", default: "You did not pay for your membership"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/kit/index.md"
        label: "Kit"
        name: "kit"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "kit-page"}
          - {label: "Title", name: "title", widget: "string", default: "Kit"}
          - {label: "Intro", name: "intro", widget: "markdown"}
