name: Build Thursdays at 1835
on:
  schedule:
    - cron: '35 18 * * 4'

jobs:
  Ubuntu:
    name: Rebuild
    runs-on: ubuntu-latest
    env:
      REBUILD_WEBHOOK_URL: ${{ secrets.REBUILD_WEBHOOK_URL }}
    steps:
      - name: POST to webhook
        run: curl -X POST -d {} $REBUILD_WEBHOOK_URL



