name: Build Saturdays at 1435
on:
  schedule:
    - cron: '35 14 * * 6'

jobs:
  Ubuntu:
    name: Rebuild
    runs-on: ubuntu-latest
    env:
      REBUILD_WEBHOOK_URL: ${{ secrets.REBUILD_WEBHOOK_URL }}
    steps:
      - name: POST to webhook
        run: curl -X POST -d {} $REBUILD_WEBHOOK_URL



